### ISSUE TITLE
CSV write truncates data

### ISSUE THREAD

**Issue by tebeka** [v3io/frames#10]
Assuming `config.toml` is
```toml
verbose = "info"

[[backends]]
name = "weather"
type = "csv"
rootDir = "/tmp/weather"
```

The run
```bash
#!/bin/bash

root_dir=/tmp/weather
rm -rf ${root_dir}
mkdir -p ${root_dir}
cp _examples/client/py/weather.csv ${root_dir}
go run cmd/framesd/framesd.go -config _t/config.toml
```
And then
```bash
PYTHONPATH=clients/py python _examples/client/py/client.py
```

You'll see the generated file is truncated.
